version: '3.8'

services:
  app:
    build: .
    container_name: gerador-orcamentos
    restart: unless-stopped
    ports:
      - "4006:3000"
    env_file:
      - .env
    networks:
      - orcamentos-network
    volumes:
      - ./arquivos:/app/arquivos
networks:
  orcamentos-network:
    driver: bridge