name: Auto Deploy to Mabus VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 2222
          script: |
            cd /opt/gerador-orcamentos
            git fetch --all
            git reset --hard origin/main
            docker compose down
            docker compose up -d --build